# Use the official Node.js image as the base image
FROM node:22-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the entire contents of the code repository to the working directory
COPY . .

# Expose port 3000 to the outside world
EXPOSE 3000

# Set the entry point to the "dist/app.js" file
CMD ["npm", "run", "dev"]
