services:
  api:
    build:
      dockerfile: "Dockerfile.dev"
    volumes:
      - ./src:/app/src
      - ./script:/app/script
      - ./nodemon.json:/app/nodemon.json
    environment:
      - IDEFIX_ADMIN_TOKENS=${IDEFIX_ADMIN_TOKENS}
      - BAN_API_URL=${BAN_API_URL}
      - BAN_API_TOKEN=${BAN_API_TOKEN}
      - API_DEPOT_URL=${API_DEPOT_URL}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
